server:
  port: 8888
spring:
  application:
    name: config
  cloud:
    config:
      fail-fast: true
      server:
        git:
          uri: git@git.dev.tencent.com:graysonli/config_server.git
          default-label: test2.0
          basedir: /mw/config/dev/
          force-pull: true
  banner:
    location: banner.txt


